# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [89]:
import numpy as np

def SM(z):
  return np.exp(z) / np.sum(np.exp(z))

def dW_NLL(x,a,y):
  return x.T *(a.T-y)

def find_z(x,W):
  return np.dot(x.T,W)

def RELU(z):
  return np.maximum(0,z)
  

 **Problem 2A**

In [90]:
z = np.array([[-1, 0, 1]]).T
print(SM(z))

[[0.09003057]
 [0.24472847]
 [0.66524096]]


**Problem 2.C-F**

In [91]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T
print(find_z(x,w))
print(SM(find_z(x,w)))
print(dW_NLL(x,SM(find_z(x,w)),y).T)

[[ 0  1 -1]]
[[0.24472847 0.66524096 0.09003057]]
[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]


In [92]:
print(w-0.5 * dW_NLL(x,SM(find_z(x,w)),y).T)
w2 = w-0.5 * dW_NLL(x,SM(find_z(x,w)),y).T
print(SM(find_z(x,w2)))


[[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]
[[0.15918761 0.77245284 0.06835955]]


**Problem 3**

In [98]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

x = np.array([[3], [14]])

z1 = np.dot(w_1.T, x) + w_1_bias
print(z1)
print(RELU(z1))
a1 = RELU(z1)
z2 = np.dot(w_2.T, a1) + w_2_bias
print(z2)
print(SM(z2))
a2 = SM(z2)
print(a2)

[[  2]
 [ 13]
 [ -4]
 [-15]]
[[ 2]
 [13]
 [ 0]
 [ 0]]
[[ 15]
 [-13]]
[[1.00000000e+00]
 [6.91440011e-13]]
[[1.00000000e+00]
 [6.91440011e-13]]


In [94]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]


In [95]:
def NLL(a, y):
  return -np.sum(y * np.log(a))

a = np.array([[0.3, 0.5, 0.2]]).T
y = np.array([[0, 0, 1]]).T

print(NLL(a, y))


1.6094379124341003
